%%
%% Autogenerated by Thrift Compiler (0.9.3)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(model_types).

-include("model_types.hrl").

-export([struct_info/1, struct_info_ext/1]).

struct_info('Complex') ->
  {struct, [{1, i16},
          {2, i16}]}
;

struct_info('Status') ->
  {struct, [{1, bool},
          {2, string}]}
;

struct_info('Result') ->
  {struct, [{1, {struct, {'model_types', 'Status'}}},
          {2, {struct, {'model_types', 'Complex'}}}]}
;

struct_info(_) -> erlang:error(function_clause).

struct_info_ext('Complex') ->
  {struct, [{1, undefined, i16, 'r', undefined},
          {2, undefined, i16, 'i', undefined}]}
;

struct_info_ext('Status') ->
  {struct, [{1, undefined, bool, 'success', undefined},
          {2, undefined, string, 'desc', undefined}]}
;

struct_info_ext('Result') ->
  {struct, [{1, undefined, {struct, {'model_types', 'Status'}}, 'status', #'Status'{}},
          {2, undefined, {struct, {'model_types', 'Complex'}}, 'result', #'Complex'{}}]}
;

struct_info_ext(_) -> erlang:error(function_clause).

