%%
%% Autogenerated by Thrift Compiler (0.9.3)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(test_thrift).
-behaviour(thrift_service).


-include("test_thrift.hrl").

-export([struct_info/1, function_info/2]).

struct_info(_) -> erlang:error(function_clause).
%%% interface
% add(This, A, B)
function_info('add', params_type) ->
  {struct, [{1, {struct, {'model_types', 'Complex'}}},
          {2, {struct, {'model_types', 'Complex'}}}]}
;
function_info('add', reply_type) ->
  {struct, {'model_types', 'Result'}};
function_info('add', exceptions) ->
  {struct, []}
;
% sub(This, A, B)
function_info('sub', params_type) ->
  {struct, [{1, {struct, {'model_types', 'Complex'}}},
          {2, {struct, {'model_types', 'Complex'}}}]}
;
function_info('sub', reply_type) ->
  {struct, {'model_types', 'Result'}};
function_info('sub', exceptions) ->
  {struct, []}
;
function_info(_Func, _Info) -> erlang:error(function_clause).

